language: python
matrix:
  fast_finish: true
  include:

    # osx
    - os: osx
      language: generic
      env: BUILD=tests PYTHON_VERSION=3.6.0 TARANTOOL_VERSION=1_6

    - os: osx
      language: generic
      env: BUILD=tests PYTHON_VERSION=3.6.0 TARANTOOL_VERSION=1_7

    # precise python3.5 Tarantool 1.6
    - os: linux
      dist: precise
      sudo: required
      language: python
      python: '3.5'
      env: BUILD=quicktests TARANTOOL_VERSION=1_6

    # trusty python3.5 Tarantool 1.6
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: '3.5'
      env: BUILD=quicktests TARANTOOL_VERSION=1_6

    # trusty python3.5 Tarantool 1.7
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: '3.5'
      env: BUILD=tests TARANTOOL_VERSION=1_7

    # trusty python3.6 Tarantool 1.7 + deploy
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: '3.6'
      env: BUILD=tests,coverage,release TARANTOOL_VERSION=1_7

cache:
  - pip

before_install:
  - ".ci/travis-before-install.sh"

install:
  - ".ci/travis-install.sh"

script:
  - ".ci/travis-tests.sh"

after_success:
  - if [[ "${BUILD}" == *coverage* ]]; then coveralls; fi

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: VJvLRYAzwzPOHtdm2gfxmvw6Ee1qnNNyeXD8fJoNZuIJ/E/nGR9CNIjIMuK69NgNcHuxjdlMl7YhNSwrF0M/sS4GP4CmJXzuvI5bH6i22wDSe0ArfwUwIyp7a9SeJuevTr6ksLVkk1i15/866keWTKtF5/XFstNDnQ957zDlEDfIUzqXQ41entnx9z9snNa0PtNNKTH5DE3Wk04NaJBqzkzllA2HQM4mkDhUeKxKHl4uPt+b75ZciA748qrR2GU0nz68CZdKZxqXEL9bXgLMX8C2MWGvP8Ikgv/LWRLvFkmPs/mLC42swSmkfPG0W+y5hBy3eAMj8W3lx7A4O3HndTFGOCfsqPt+fti9RLCHkVLkijnZMmvKqT96Y9ppWd+szFZnzEw/PyZIlLXMixrW/dFe7fOvWM9qBLjCZ+l6X/soe0so+XW/KSUtXMzy429063YA6ht1PAnQD2lJrF2ldQVHeC5WTprF2ncnTADfbBA5mbgdclUsnSAx3bErcp11RrAIpOVWF268UfnsQ8GJVMK5z86XUAfE6Epe4GxC7meFNHGfLTzV6RoxvzKyZQTcLtTVjjHyjrHptTbF/x49OkD6jZGspi+3YS8yJVJEWXAYHMsbXneMmT4PutP4reQRk3HLnnFpUFUeaNaHxYWjXdBsCNjqTSDVZiftVak/y7A=
    file_glob: true
    file: dist/asynctnt*.tar.gz
    on:
      repo: igorcoding/asynctnt
      tags: true
      condition: '"${BUILD}" == *release*'

  - provider: script
    script: .ci/travis-release.sh
    on:
      tags: true
      condition: '"${BUILD}" == *release*'
