language: python
env:
  global:
  - ENCRYPTION_LABEL: "8db6dbddd29a"
  - COMMIT_AUTHOR_EMAIL: "igorcoding@gmail.com"

matrix:
  fast_finish: true
  include:

    # osx
    - os: osx
      language: generic
      env: BUILD=tests PYTHON_VERSION=3.6.0 TARANTOOL_VERSION=1_9

    - os: osx
      language: generic
      env: BUILD=tests PYTHON_VERSION=3.6.0 TARANTOOL_VERSION=1_9

    - os: osx
      language: generic
      env: BUILD=tests PYTHON_VERSION=3.7.0 TARANTOOL_VERSION=1_9

    - os: osx
      language: generic
      env: BUILD=tests PYTHON_VERSION=3.7.0 TARANTOOL_VERSION=1_9

    # precise python3.5 Tarantool 1.6
    - os: linux
      dist: precise
      sudo: required
      language: python
      python: '3.5'
      env: BUILD=quicktests TARANTOOL_VERSION=1_6

    # trusty python3.5 Tarantool 1.6
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: '3.5'
      env: BUILD=quicktests TARANTOOL_VERSION=1_6

    # trusty python3.5 Tarantool 1.7
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: '3.5'
      env: BUILD=tests TARANTOOL_VERSION=1_7

    # trusty python3.5 Tarantool 1.9
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: '3.5'
      env: BUILD=tests TARANTOOL_VERSION=1_9

    # trusty python3.6 Tarantool 1.9
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: '3.6'
      env: BUILD=tests TARANTOOL_VERSION=1_9

    # trusty python3.7 Tarantool 1.9
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: '3.7'
      env: BUILD=tests TARANTOOL_VERSION=1_9

    # trusty python3.6 Tarantool 1.9 + deploy
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: '3.6'
      env: BUILD=tests,docs,coverage,release TARANTOOL_VERSION=1_9

cache:
  - pip

before_install:
  - ".ci/travis-before-install.sh"

install:
  - ".ci/travis-install.sh"

script:
  - ".ci/travis-tests.sh"
  - ".ci/travis-build-docs.sh"

after_success:
  - if [[ "${BUILD}" == *coverage* ]]; then coveralls; fi

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: 10qOBRZ6duGCBw2SXJbJLxkBhfPKnnwvGmS6tBS59BixqjWJOhEAMHws+GQxmNY6rYiGMFKCzMLB7lJwZfycf2oD110qcoubjM4Unrc/iRZeWXazyzbm4zL4m9Ubfdbc6TI59CSTCVeeK6g7EWewDs+5VkTbCZCteim9L5dD8iG+i3w+0F9yE/m3iZTZBCIKkZEpofijc3FHjly1bZ8CLJLEVya8wzMjZuHdQimam9ur/Hn27M96uNyHgqlk8V9jbchdHfMhy6pKmTbXGNk4CcgRr2Uy0vX3pRFYrV5Y9tVL5q7BnKmn6nQgIC79OGKQysWP7zal8UgE66qwsrGVLBUsj8ij7hw/apdZ0Wg+0fkdQqPghsoGSO9n2VCn2hPd/dolc2seceFuy7znvpYyoE++ysXWGaU4ExfUvJmNRR+35nRvJqncpaOAQcAXAQ59sy0bc4I0K/sjL4DgIkiKnhF13yMF3fqsfu2oYBk6UUlF13AdOaizDwqGZ/KO5OlozCG2naQocaSg5L/DXLFgcKNmUg60vixrnMW0rnGAS64JkGBHqASp+J6xSv7h1tA9Az0CLmKFqEaPr9vt0nfxYFI/GNRzIvYGv5bznDtLek0dsHkKZXIyZW/9w+zyp6ja9F1Q22Xr0wHolnqtYAJa1EcoUAfxyByLu6N1TsWXihU=
    file_glob: true
    file: dist/asynctnt*.tar.gz
    on:
      repo: igorcoding/asynctnt
      tags: true
      condition: '"${BUILD}" == *release*'

  - provider: script
    script: .ci/travis-release.sh
    on:
      tags: true
      condition: '"${BUILD}" == *release*'
