language: python

matrix:
  fast_finish: true
  include:
    # osx
    - os: osx
      language: generic
      env: BUILD=tests PYTHON_VERSION=3.5.2 TARANTOOL_VERSION=1_6

    - os: osx
      language: generic
      env: BUILD=tests PYTHON_VERSION=3.6.0 TARANTOOL_VERSION=1_6

    - os: osx
      language: generic
      env: BUILD=tests PYTHON_VERSION=3.5.2 TARANTOOL_VERSION=1_7

    - os: osx
      language: generic
      env: BUILD=tests PYTHON_VERSION=3.6.0 TARANTOOL_VERSION=1_7

    # precise
    - os: linux
      dist: precise
      sudo: required
      language: python
      python: "3.5"
      env: BUILD=quicktests TARANTOOL_VERSION=1_6

    - os: linux
      dist: precise
      sudo: required
      language: python
      python: "3.5"
      env: BUILD=quicktests TARANTOOL_VERSION=1_7

    # trusty
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: "3.5"
      env: BUILD=quicktests TARANTOOL_VERSION=1_6

    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: "3.5"
      env: BUILD=quicktests TARANTOOL_VERSION=1_7

    # latest tarantool
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: "3.5"
      env: BUILD=tests TARANTOOL_VERSION=1_7

    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: "3.6"
      env: BUILD=tests TARANTOOL_VERSION=1_7

cache:
  - pip

before_install:
  - .ci/travis-before-install.sh

install:
    - .ci/travis-install.sh

script:
    - .ci/travis-tests.sh
